### ISSUE TITLE
[Sleepless Hollow] Crash corrupted my save file

### ISSUE THREAD

**Issue by AlbertHamik** [SpaceManiac/HamSandwich#13]
Sleepless Hollow is an absurdly difficult game, and a crash in the Bones tomb while fighting the one flames miniboss when it killed me corrupted my save and deleted the Earsplitter from my inventory, rendering the game incompleteable as far as I can tell (this is my first real playthrough). I had beaten two other bosses prior. I was playing on the Linux build also.

**Comment by SpaceManiac** [comment]
Most unfortuitous. If you wish, you can upload your save and I can try to fix it with hex editing, though I might be rusty at doing so.

There are two issues: the crash, and that crashing corrupted the save. I can likely engineer the save system so that crashes do not corrupt the save anymore, but it will be difficult to trace down the crash without any additional detail.

**Comment by AlbertHamik** [comment]
Well I started from scratch and managed to catch back up (tl;dr Sleepless Hollow maybe the weaker title I've played from Hamumu, but it was still an okay time FTMP). I figure it would be nice to have a more robust backup system for saves in case this stuff ever happens for someone else in any of the big titles on the hamsandwich platform.
