### ISSUE TITLE
Sounds not playing, severity of issue differs depending on game

### ISSUE THREAD

**Issue by AlbertHamik** [SpaceManiac/HamSandwich#14]
There appears to be an issue with sounds. Many sounds will not play if there is multiple sound triggering events going on. Actually, certain games that shouldn't have that much going on ALSO suffer from severe sound drops, and it might be related to the sound distance stuff of the original code. Spooky Castle features some of the most severe sound drops, sometimes the game is just silent in spite of anything going on. This issue happens across all versions of the engine I've played, from the browser build, to the Linux build, and even the Windows build.

Also as an aside, if you have plans to revamp the sound engine or replace it, have you by chance looked into miniaudio (https://miniaud.io/)?

**Comment by SpaceManiac** [comment]
There are or were big issues with the port of the positional sound calculations in some games. I did some cross-comparison and I think Supreme With Cheese is now true to v7.8, but the other games haven't received the same care yet.

The original versions of the positional sound calculations _do_ have some weirdness: Supreme at 10% sound, for example, completely silences sounds near the edge of the screen, because "10% volume" actually subtracts some multiple of 90 from the volume after positional calculations, rather than reducing it by 90%.

The problem is probably in the "jamulsound" module that acts as a middleman between SDL_mixer and the rest of the code.

I haven't looked into miniaudio. So far SDL_mixer has done everything necessary, except that the web version doesn't support pitch-shifting effects.

**Comment by AlbertHamik** [comment]
Yeah I realized after mentioning it that you were probably making do with SDL_mixer just fine. I don't know if there'd be any advantage to miniaudio but I know a few projects have made good use of it. It has some benefits.

EDIT: BTW not really related to the issue at hand but have you had any thoughts on upgrading engine support for alternative image formats like .png? For something like remastering the visuals above the 256 color limit and heavy banding that is distinctive of the old Hamumu games. I was joking with someone these games need true 3D rendering (SM64 Render96 style) but high/true color image support would be just as good, and probably less effort.

**Comment by SpaceManiac** [comment]
> remastering the visuals above the 256 color limit

As it is there seems to be no good way to actually _do_ this 3D model remastering. They are baked at the resolution and color depth they are and the originals are believed lost. If putting in the effort to replace all the graphics, one might as well create their own game.

**Comment by AlbertHamik** [comment]
Well I just meant small improvements could be made like image filtering (neural network based methods, perhaps) to remove the harsh posterized lighting on models, among other things. It's not impossible to improve the visuals if someone had the ability to do so, but it would require lifting the 256 color limitation of the shared game engines' feature set. The SM64 Render96 thing is just an extreme example I gave but the simpler methodology I was thinking of could be automated and made into a patch easily.

Also to loop this back around to audio, apologies on that detour, I'm wondering if it'd be possible to replace sounds in the game to introduce cleaned up audio because some of the audio in the old games are quite compressed or have weird static sounds to them (ex: Loonyland's SFX for pausing or receiving new items). Obviously it could work via the addons system of hamsandwich.

**Comment by SpaceManiac** [comment]
Ah, I see. I think I would want to see some out-of-engine mockups and maybe workshop them with the community before committing to rewriting the rendering engine, which is a big project, since almost all code that draws anything is tied into the 256-color limitation. Something that could run as a postprocessing filter on the finished 256-color frame would be much simpler.

Overriding individual audio files is indeed quite easy with the addon system. Someone would have to actually create the replacements.

**Comment by AlbertHamik** [comment]
Well I was thinking it may be a long term goal of yours to work out improving the rendering engine regardless, seeing as it can stand to perform more optimally on modern systems still. Though I think you've managed to get it working better already with the work you have done thus far, there's still some aspects of almost every engine within hamsandwich that could stand to be tweaked for optimal performance by modern standards. 

Some of these games can fluctuate in framerate, and though it's not nearly as bad as the vanilla OG builds of the respective games running on the same systems, it's still worse than you'd expect of an oldschool 2D game engine codebase that's over 20 years old at the most, which I understand is mostly coding optimizations that have been lost on modern systems. Anyways I'll quit sidetracking because clearly we both know there's not much else to talk about.
