### ISSUE TITLE
Actual binaries

### ISSUE THREAD

**Issue by Tyler-Osborne** [SpaceManiac/HamSandwich#6]
Is there a way to compile these games and have them as actual executables or do you have to use the run file?

**Comment by SpaceManiac** [comment]
After running `make` (which is one step in the `./run` script), the `.exe` files can be found inside the `build/` folder, for example at `build/gcc-debug/supreme/supreme.exe`.

If you want to run the `.exe` standalone, you will have to put it in a folder with the assets and manually collect all the `.dll` files it needs into the same folder. You can list all `.dll` files in the project with the command `find . -name '*.dll'`, and either follow the error messages or use the "ntldd" tool to find out which ones are required.

This process hasn't yet been automated.

**Comment by SpaceManiac** [comment]
I've automated the process for the MSVC build. Double-clicking `tools/msvc/Create Release Zip.bat` will compile the games in release mode, collect the `.exe`s and `.dll`s into the `build/pkgroot/` folder, and create a `.zip` file. You can then copy those files or that `.zip` to another location and use them without the `./run` script or Visual Studio.

Additionally, the `.exe` files will show a prompt on how to set them up if run in a folder without either the game's installers from https://hamumu.itch.io or an existing installation of the game available.

Official builds are available at https://wombat.platymuus.com/hamsandwich/release/.

I haven't automated the MinGW builds yet because the DLL situation isn't as convenient.

**Comment by SpaceManiac** [comment]
For coders, `make install` will now place publishable binaries into the `build/install/` folder.

For players, binaries are now published on a regular basis to https://spacemaniac.itch.io/hamsandwich.
